version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: demosqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ffADFfcfgfg$5#@%%#@@#dfgdf!
      - MSSQL_PID=Standard
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql
