name: "demo-nuke-items-api"
concurrency: demo-nuke-items-api

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  SETUP:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x

      - name: Install Nuke
        run: dotnet tool install Nuke.GlobalTool --global
  DEV:
    name: DEV
    needs: SETUP
    uses: ./.github/workflows/dev.yml
    with:
      environment: dev
      apiKey: "${{ vars.APIKEY }}"
    secrets:
      password: "${{ secrets.PASSWORD }}"    