name: "demo-nuke-items-api"
concurrency: demo-nuke-items-api

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  DEV:
    name: DEV
    uses: ./.github/workflows/ci-pipeline.yml
    with:
      environment: dev
      apiKey: ${{ env.APIKEY }}
    secrets:
      password: ${{ secrets.PASSWORD }}    