name: "demo-nuke-items-api"
concurrency: demo-nuke-items-api

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  DEV:
    name: DEV
    environment: dev
    uses: ${{ github.workspace }}/ci-pipeline.yml    
    with:
      environment: dev
      apiKey: ${{ vars.APIKEY }}
    secrets:
      password: ${{ secrets.PASSWORD }}    