name: "demo-nuke-items-api"
concurrency: demo-nuke-items-api

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  DEV:
    name: DEV
    uses: ${{ github.workspace }}/workflows/ci-pipeline.yml    
    with:
      environment: dev    